zd_dict = {}
zd_dict.update({
  "C1-6": ["C", "CF", "R", "R_QAH"],
  "C1-6A": ["C", "CF", "R", "R_QAH"],
  "C1-7": ["C", "CF", "R", "R_QAH"],
  "C1-7A": ["C", "CF", "R", "R_QAH"],
  "C1-8": ["C", "CF", "R", "R_QAH"],
  "C1-8A": ["C", "CF", "R", "R_QAH"],
  "C1-8X": ["C", "CF", "R", "R_QAH"],
  "C1-9": ["C", "CF", "R", "R_QAH"],
  "C1-9A": ["C", "CF", "R", "R_QAH"],
  "C2-6": ["C", "CF", "R", "R_QAH"],
  "C2-6A": ["C", "CF", "R", "R_QAH"],
  "C2-7": ["C", "CF", "R", "R_QAH"],
  "C2-7A": ["C", "CF", "R", "R_QAH"],
  "C2-7X": ["C", "CF", "R", "R_QAH"],
  "C2-8": ["C", "CF", "R", "R_QAH"],
  "C2-8A": ["C", "CF", "R", "R_QAH"],
  "C3": ["C", "CF", "R"],
  "C3A": ["C", "CF", "R"],
  "C4-1": ["C", "CF", "R"],
  "C4-11": ["C", "CF", "R", "R_QAH"],
  "C4-11A": ["C", "CF", "R", "R_QAH"],
  "C4-12": ["C", "CF", "R", "R_QAH"],
  "C4-2": ["C", "CF", "R", "R_QAH"],
  "C4-2A": ["C", "CF", "R", "R_QAH"],
  "C4-2F": ["C", "CF", "R", "R_QAH"],
  "C4-3": ["C", "CF", "R", "R_QAH"],
  "C4-3A": ["C", "CF", "R", "R_QAH"],
  "C4-4": ["C", "CF", "R", "R_QAH"],
  "C4-4A": ["C", "CF", "R", "R_QAH"],
  "C4-4D": ["C", "CF", "R", "R_QAH"],
  "C4-4L": ["C", "CF", "R", "R_QAH"],
  "C4-5": ["C", "CF", "R", "R_QAH"],
  "C4-5A": ["C", "CF", "R", "R_QAH"],
  "C4-5D": ["C", "CF", "R", "R_QAH"],
  "C4-5X": ["C", "CF", "R", "R_QAH"],
  "C4-6": ["C", "CF", "R", "R_QAH"],
  "C4-6A": ["C", "CF", "R", "R_QAH"],
  "C4-7": ["C", "CF", "R", "R_QAH"],
  "C4-7A": ["C", "CF", "R", "R_QAH"],
  "C4-8": ["C", "CF", "R", "R_QAH"],
  "C4-9": ["C", "CF", "R", "R_QAH"],
  "C5-1": ["C", "CF", "R", "R_QAH"],
  "C5-1A": ["C", "CF", "R", "R_QAH"],
  "C5-2": ["C", "CF", "R", "R_QAH"],
  "C5-2.5": ["C", "CF", "R", "R_QAH"],
  "C5-2A": ["C", "CF", "R", "R_QAH"],
  "C5-3": ["C", "CF", "R", "R_QAH"],
  "C5-3.5": ["C", "CF", "R", "R_QAH"],
  "C5-4": ["C", "CF", "R", "R_QAH"],
  "C5-5": ["C", "CF", "R", "R_QAH"],
  "C5-P": ["C", "CF", "R", "R_QAH"],
  "C6-1": ["C", "CF", "R", "R_QAH"],
  "C6-11": ["C", "CF", "R", "R_QAH"],
  "C6-12": ["C", "CF", "R", "R_QAH"],
  "C6-1A": ["C", "CF", "R", "R_QAH"],
  "C6-1G": ["C", "CF", "R", "R_QAH"],
  "C6-2": ["C", "CF", "R", "R_QAH"],
  "C6-2A": ["C", "CF", "R", "R_QAH"],
  "C6-2G": ["C", "CF", "R", "R_QAH"],
  "C6-2M": ["C", "CF", "R", "R_QAH"],
  "C6-3": ["C", "CF", "R", "R_QAH"],
  "C6-3A": ["C", "CF", "R", "R_QAH"],
  "C6-3D": ["C", "CF", "R", "R_QAH"],
  "C6-3X": ["C", "CF", "R", "R_QAH"],
  "C6-4": ["C", "CF", "R", "R_QAH"],
  "C6-4.5": ["C", "CF", "R", "R_QAH"],
  "C6-4A": ["C", "CF", "R", "R_QAH"],
  "C6-4M": ["C", "CF", "R", "R_QAH"],
  "C6-4X": ["C", "CF", "R", "R_QAH"],
  "C6-5": ["C", "CF", "R", "R_QAH"],
  "C6-5.5": ["C", "CF", "R", "R_QAH"],
  "C6-6": ["C", "CF", "R", "R_QAH"],
  "C6-6.5": ["C", "CF", "R", "R_QAH"],
  "C6-7": ["C", "CF", "R", "R_QAH"],
  "C6-7.5": ["C", "CF", "R", "R_QAH"],
  "C6-7T": ["C", "CF", "R", "R_QAH"],
  "C6-8": ["C", "CF", "R", "R_QAH"],
  "C6-9": ["C", "CF", "R", "R_QAH"],
  "C7-1": ["C", "CF"],
  "C7-2": ["C", "CF"],
  "C7-3": ["C", "CF"],
  "C7-4": ["C", "CF"],
  "C7-5": ["C", "CF"],
  "C7-6": ["C", "CF"],
  "C7-7": ["C", "CF"],
  "C7-8": ["C", "CF"],
  "C7-9": ["C", "CF"],
  "C8-1": ["C", "CF"],
  "C8-2": ["C", "CF"],
  "C8-3": ["C", "CF"],
  "C8-4": ["C", "CF"],
  "CO R1-R5": ["C", "CF", "R"],
  "CO R6-R12": ["C", "CF", "R", "R_QAH"]
})

zd_dict.update({
  "M1-1": ["C", "CF", "M"],
  "M1-1/R5": ["C", "CF", "M", "R"],
  "M1-1/R6A": ["C", "CF", "M", "R", "R_QAH"],
  "M1-1/R7-2": ["C", "CF", "M", "R", "R_QAH"],
  "M1-1/R7D": ["C", "CF", "M", "R", "R_QAH"],
  "M1-1A": ["C", "CF", "M"],
  "M1-1A/R6B": ["C", "CF", "M", "R", "R_QAH"],
  "M1-1A/R7-3": ["C", "CF", "M", "R", "R_QAH"],
  "M1-1D": ["C", "CF", "M", "R"],
  "M1-2": ["C", "CF", "M"],
  "M1-2/R5B": ["C", "CF", "M", "R"],
  "M1-2/R5D": ["C", "CF", "M", "R"],
  "M1-2/R6": ["C", "CF", "M", "R", "R_QAH"],
  "M1-2/R6A": ["C", "CF", "M", "R", "R_QAH"],
  "M1-2/R6B": ["C", "CF", "M", "R", "R_QAH"],
  "M1-2/R7-1": ["C", "CF", "M", "R", "R_QAH"],
  "M1-2/R7-2": ["C", "CF", "M", "R", "R_QAH"],
  "M1-2/R7A": ["C", "CF", "M", "R", "R_QAH"],
  "M1-2/R8": ["C", "CF", "M", "R", "R_QAH"],
  "M1-2/R8A": ["C", "CF", "M", "R", "R_QAH"],
  "M1-2A": ["C", "CF", "M"],
  "M1-2A/R6A": ["C", "CF", "M", "R", "R_QAH"],
  "M1-2A/R7D": ["C", "CF", "M", "R", "R_QAH"],
  "M1-2D": ["C", "CF", "M", "R"],
  "M1-3": ["C", "CF", "M"],
  "M1-3/R7D": ["C", "CF", "M", "R", "R_QAH"],
  "M1-3/R7X": ["C", "CF", "M", "R", "R_QAH"],
  "M1-3/R8": ["C", "CF", "M", "R", "R_QAH"],
  "M1-3A": ["C", "CF", "M"],
  "M1-3A/R7D": ["C", "CF", "M", "R", "R_QAH"],
  "M1-3D": ["C", "CF", "M", "R"],
  "M1-4": ["C", "CF", "M"],
  "M1-4/R6": ["C", "CF", "M", "R", "R_QAH"],
  "M1-4/R6A": ["C", "CF", "M", "R", "R_QAH"],
  "M1-4/R6B": ["C", "CF", "M", "R", "R_QAH"],
  "M1-4/R7-2": ["C", "CF", "M", "R", "R_QAH"],
  "M1-4/R7-3": ["C", "CF", "M", "R", "R_QAH"],
  "M1-4/R7A": ["C", "CF", "M", "R", "R_QAH"],
  "M1-4/R7D": ["C", "CF", "M", "R", "R_QAH"],
  "M1-4/R7X": ["C", "CF", "M", "R", "R_QAH"],
  "M1-4/R8A": ["C", "CF", "M", "R", "R_QAH"],
  "M1-4/R9": ["C", "CF", "M", "R", "R_QAH"],
  "M1-4/R9A": ["C", "CF", "M", "R", "R_QAH"],
  "M1-4A": ["C", "CF", "M"],
  "M1-4A/R9A": ["C", "CF", "M", "R", "R_QAH"],
  "M1-4D": ["C", "CF", "M", "R"],
  "M1-5": ["C", "CF", "M"],
  "M1-5/R10": ["C", "CF", "M", "R", "R_QAH"],
  "M1-5/R6A": ["C", "CF", "M", "R", "R_QAH"],
  "M1-5/R7-2": ["C", "CF", "M", "R", "R_QAH"],
  "M1-5/R7-3": ["C", "CF", "M", "R", "R_QAH"],
  "M1-5/R7D": ["C", "CF", "M", "R", "R_QAH"],
  "M1-5/R7X": ["C", "CF", "M", "R", "R_QAH"],
  "M1-5/R8A": ["C", "CF", "M", "R", "R_QAH"],
  "M1-5/R9": ["C", "CF", "M", "R", "R_QAH"],
  "M1-5/R9-1": ["C", "CF", "M", "R", "R_QAH"],
  "M1-5/R9A": ["C", "CF", "M", "R", "R_QAH"],
  "M1-5/R9X": ["C", "CF", "M", "R", "R_QAH"],
  "M1-5A": ["C", "CF", "M"],
  "M1-5B": ["C", "CF", "M"],
  "M1-5D": ["C", "CF", "M", "R"],
  "M1-5M": ["C", "CF", "M"],
  "M1-6": ["C", "CF", "M"],
  "M1-6/R10": ["C", "CF", "M", "R", "R_QAH"],
  "M1-6/R8X": ["C", "CF", "M", "R", "R_QAH"],
  "M1-6/R9": ["C", "CF", "M", "R", "R_QAH"],
  "M1-6A": ["C", "CF", "M"],
  "M1-6D": ["C", "CF", "M", "R", "R_QAH"],
  "M1-6M": ["C", "CF", "M"],
  "M1-7A": ["C", "CF", "M"],
  "M1-8A": ["C", "CF", "M"],
  "M1-9A": ["C", "CF", "M"],
  "M2-1": ["C", "CF", "M"],
  "M2-1A": ["C", "CF", "M"],
  "M2-2": ["C", "CF", "M"],
  "M2-2A": ["C", "CF", "M"],
  "M2-3": ["C", "CF", "M"],
  "M2-3A": ["C", "CF", "M"],
  "M2-4": ["C", "CF", "M"],
  "M2-4A": ["C", "CF", "M"],
  "M3-1": ["C", "CF", "M"],
  "M3-1A": ["C", "CF", "M"],
  "M3-2": ["C", "CF", "M"],
  "M3-2A": ["C", "CF", "M"]
})


zd_dict.update({
  "R1-1": ["CF", "R"],
  "R1-2": ["CF", "R"],
  "R1-2A": ["CF", "R"],
  "R10": ["CF", "R", "R_QAH"],
  "R10A": ["CF", "R", "R_QAH"],
  "R10H": ["C", "CF", "R", "R_QAH"],
  "R10X": ["CF", "R", "R_QAH"],
  "R11": ["CF", "R", "R_QAH"],
  "R11A": ["CF", "R", "R_QAH"],
  "R12": ["CF", "R", "R_QAH"],
  "R2": ["CF", "R"],
  "R2A": ["CF", "R"],
  "R2X": ["CF", "R"],
  "R3-1": ["CF", "R"],
  "R3-2": ["CF", "R"],
  "R3A": ["CF", "R"],
  "R3X": ["CF", "R"],
  "R4": ["CF", "R"],
  "R4-1": ["CF", "R"],
  "R4A": ["CF", "R"],
  "R4B": ["CF", "R"],
  "R5": ["CF", "R"],
  "R5A": ["CF", "R"],
  "R5B": ["CF", "R"],
  "R5D": ["CF", "R"],
  "R6": ["CF", "R", "R_QAH"],
  "R6-1": ["CF", "R", "R_QAH"],
  "R6-2": ["CF", "R", "R_QAH"],
  "R6A": ["CF", "R", "R_QAH"],
  "R6B": ["CF", "R", "R_QAH"],
  "R6D": ["CF", "R", "R_QAH"],
  "R7-1": ["CF", "R", "R_QAH"],
  "R7-2": ["CF", "R", "R_QAH"],
  "R7-3": ["CF", "R", "R_QAH"],
  "R7A": ["CF", "R", "R_QAH"],
  "R7B": ["CF", "R", "R_QAH"],
  "R7D": ["CF", "R", "R_QAH"],
  "R7X": ["CF", "R", "R_QAH"],
  "R8": ["CF", "R", "R_QAH"],
  "R8A": ["CF", "R", "R_QAH"],
  "R8B": ["CF", "R", "R_QAH"],
  "R8X": ["CF", "R", "R_QAH"],
  "R9": ["CF", "R", "R_QAH"],
  "R9-1": ["CF", "R", "R_QAH"],
  "R9A": ["CF", "R", "R_QAH"],
  "R9D": ["CF", "R", "R_QAH"],
  "R9X": ["CF", "R", "R_QAH"]
})

def permited_uses(zonedist):
    zd = zonedist
    return zd_dict.get(zd,None)